### ISSUE TITLE
The "show outline" seems failed. 

### ISSUE THREAD

**Issue by SFYeh** [GorvGoyl/Notion-Boost-browser-extension#103]
The "show outline"  failed on my device, not sure is there anyone encountered the same probelm.  I can no longer click on the bar, and it even move to the layer under the content of notion. My Chrome version is  98.0.4758.102.

**Comment by XuGuangnian** [comment]
So am I

**Comment by yanspirit** [comment]
me too

**Comment by GorvGoyl** [comment]
thanks for reporting. Notion (again) updated their UI and it caused issues with NB. Will release a new version soon.

**Comment by GorvGoyl** [comment]
fixed
