### ISSUE TITLE
[bugs] Table can not at the correct align when outline is enabled

### ISSUE THREAD

**Issue by finach** [GorvGoyl/Notion-Boost-browser-extension#106]
![image](https://user-images.githubusercontent.com/96366890/156911724-d748b38a-76f2-4d61-83ff-7d2cabdf6c5e.png)

**Comment by GorvGoyl** [comment]
It seems to be aligning fine for me. could you share the public URL of the demo notion page with the table so that I could debug it?

**Comment by finach** [comment]
It is happen when I enable notion official left bar. I have been tested it also can not observed on share link ☹
but also attached here. https://useful-tumble-0d7.notion.site/General-6993b87a66cd4734b0c797d656d64806

![image](https://user-images.githubusercontent.com/96366890/157057092-dba8befd-972b-4f32-81bd-c7ccb5a6d61f.png)

**Comment by finach** [comment]
There is fixed on 3.1.0
