### ISSUE TITLE
Ackward display when using "Show outline" and "full width for all pages" with a page with comments

### ISSUE THREAD

**Issue by frohlichcortezh** [GorvGoyl/Notion-Boost-browser-extension#116]
![image](https://user-images.githubusercontent.com/26347102/161792646-3c97abfd-4c25-4d92-8db5-2a4eacf11455.png)

**Comment by GorvGoyl** [comment]
fixed in https://github.com/GorvGoyl/Notion-Boost-browser-extension/pull/123
