### ISSUE TITLE
Wrong style of simple table with outline and sidebar open

### ISSUE THREAD

**Issue by WodahsOrez** [GorvGoyl/Notion-Boost-browser-extension#119]
It looks right with sidebar
![image](https://user-images.githubusercontent.com/41291430/162626628-6ec90c68-6be5-456b-8db6-033b0698b227.png)
but it looks wrong when i open outline
![image](https://user-images.githubusercontent.com/41291430/162626661-1aa33204-40d7-4280-be02-476b1598d8b1.png)
it doesn't change significantly without sidebar
![image](https://user-images.githubusercontent.com/41291430/162626750-254972b3-4db5-4df9-86eb-6224f101b45c.png)
![image](https://user-images.githubusercontent.com/41291430/162626816-e339411e-f219-4b6f-924b-76712cab020d.png)

**Comment by lilin90** [comment]
@GorvGoyl I also encountered this issue and it still exists even with https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/204051f387cc40338a691691628c8407bbc12c63. Would you please take a look again? Thanks!

When **Full width** is enabled, the simple table can't display well:
![image](https://user-images.githubusercontent.com/30922556/178243110-34c15d29-a7e7-4707-987f-1db4a5b7f749.png)

When **Full width** is not enabled, the display is acceptable but the table is not left-aligned with the heading:
![image](https://user-images.githubusercontent.com/30922556/178243664-14689ed3-b0f9-4a0e-b1ce-690d38561fa0.png)

**Comment by GorvGoyl** [comment]
the latest notion update broke this feature. I'm working on it now and ship the new update soon

**Comment by GorvGoyl** [comment]
thanks for reporting. it has been fixed in v.3.1.2
