### ISSUE TITLE
Suggestions re: "Show full text on hover" 

### ISSUE THREAD

**Issue by fcherman** [GorvGoyl/Notion-Boost-browser-extension#12]
1. Recognize and ignore transient hovers, such as those that occur during navigation (vs. reading).  Then ease the transition between truncated text and full text and between one cell or row and another. The current experience is unpleasantly jerky and disorienting – especially when triggered dozens of times in rapid succession as I move the cursor for navigation purposes.

2. Detect and ignore tables/cells with wrapped text since the complete text is already visible, and the feature doesn't work properly on wrapped cells (see video).

Thanks for the good work!

https://user-images.githubusercontent.com/59314/104859796-8a396a00-58dc-11eb-90ae-157a63841903.mov

**Comment by GorvGoyl** [comment]
Thanks for the feedback. agree on your points. I mistakenly ignored the test case when wrapped cells.

**Comment by peinan** [comment]
In addition, it would be nice if the **page icons** are considered when showing the full text on hover.

e.g.,

Original Table Row:
`| 🤗 Lorem Ipsum is simply dummy text of the | Second Column |`
With hovering in Notion Boost 1.7:
`| Lorem Ipsum is simply dummy text of the printing and typesetting industry.`
Ideal behavior:
`| 🤗 Lorem Ipsum is simply dummy text of the printing and typesetting industry.`

Thank you for the excellent extension!

**Comment by GorvGoyl** [comment]
coming to next release

**Comment by fcherman** [comment]
> Thanks for the feedback. agree on your points. I mistakenly ignored the test case when wrapped cells.

You did it! Thanks a bunch!
