### ISSUE TITLE
"Show code line numbers" is displayed incorrectly.

### ISSUE THREAD

**Issue by Sia819** [GorvGoyl/Notion-Boost-browser-extension#121]
![image](https://user-images.githubusercontent.com/18740181/168567032-4bde0471-72f9-4b64-9ed1-126f58371119.png)

I mainly use Notion boost as a Firefox extension.
Sometimes, when you create a code spinet with "/code" in Notion, the code line is displayed on the right as shown in the image above.

In this case, refreshing the page with Ctrl + R temporarily solves it, but soon after writing the document, this phenomenon often repeats again.

**Comment by GorvGoyl** [comment]
thanks for reporting. it has been fixed in v.3.1.2
