### ISSUE TITLE
Database with wrong align when outline enable start from 3.1.0

### ISSUE THREAD

**Issue by finach** [GorvGoyl/Notion-Boost-browser-extension#128]
![image](https://user-images.githubusercontent.com/96366890/169697583-047604f6-3e86-4586-8571-e284950ac500.png)

**Comment by GorvGoyl** [comment]
I'm not able to reproduce this bug, could you add more details or perhaps a link to the page where this issue is happening

**Comment by finach** [comment]
Find the detail steps.
1. disable extension outline
2. disable full width in **notion setting**
3. enable extension outline

Below steps will not happen
1. disable extension outline
2. enable full width in notion setting
3. enable extension outline

So I think the different is that enable/disable full width in notion default setting or not.

Thanks

**Comment by chiyang10000** [comment]
@GorvGoyl The Extension released on May 22(quoted from the Chrome shop) seems have not yet included the fix. 👀

**Comment by GorvGoyl** [comment]
thanks for reporting. it has been fixed in v.3.1.2
