### ISSUE TITLE
"Open full page instead of preview" feature not working

### ISSUE THREAD

**Issue by Jfran94** [GorvGoyl/Notion-Boost-browser-extension#135]
Hi, the extension isn't bypassing previews.

I tried updating my Chrome browser (Version 103.0.5060.66 Official Build 64-bit) and removing/adding the extension. I also tried toggling this feature on and off.

Still no luck!

All other features seem to be working though.

**Comment by GorvGoyl** [comment]
thanks will look into it

**Comment by jsduarte07** [comment]
Hi, 
I am experience the same issue... It's a pity because this feature "open the page instead of preview" is actually the main reason that took me to use Notion Boost. 
All in all congratulations and thank you so much for this amazing tool.

**Comment by LuisaCF** [comment]
Hi, same here :)

**Comment by s-weppe** [comment]
Also same here - great work tho guys, Notion is a lot more palatable since I've installed your plugin!

**Comment by jsduarte07** [comment]
Hi @GorvGoyl. Any news on this issue? Thanks.

**Comment by justanamefornow** [comment]
Please fix this 💖💖💖💖💖💖💖💖💖💖💖💖💖💖

**Comment by jsduarte07** [comment]
> Great News!
> 
> For those who were patiently waiting for full page to be fixed, Notion just integrated this feature!
> 
> There are also two more options: "Side View" and "Center Peak"

Where can we see these options?

**Comment by Jfran94** [comment]
> Where can we see these options?

Open an existing database (table, board, etc) and you should be presented with the side view (like screenshot below). 

![image](https://user-images.githubusercontent.com/108409990/180096267-b74ccda2-e0f3-4100-a26a-27a2e61b42b5.png)

Simply click on the full page option if you want it applied to that database temporarily.

If you want it to permanently default to full page, you must first click on "Edit view default" then click "Full Page"

Note: If you're not presented with side view after clicking a database, it's possible that they only enabled the feature on my account so far (since I sent this feature request to them). If that's the case it might take a while for this feature to be rolled out to every account.

**Comment by jsduarte07** [comment]
> > Where can we see these options?
> 
> Open an existing database (table, board, etc) and you should be presented with the side peek (like screenshot below).
> 
> ![image](https://user-images.githubusercontent.com/108409990/180096267-b74ccda2-e0f3-4100-a26a-27a2e61b42b5.png)
> 
> Simply click on the full page option if you want it applied to that database temporarily.
> 
> If you want it to permanently default to full page, you must first click on "Edit view default" then click "Full Page"
> 
> Note: If you're not presented with side peek after clicking a database, it's possible that they only enabled the feature on my account so far (since I sent this feature request to them). If that's the case it might take a while for this feature to be rolled out to every account.

Thanks for your help and your detailed answer!
I don't see it in my Notion though. 
Guess I will be waiting for the magical hands of @GorvGoyl still :)

**Comment by GorvGoyl** [comment]
fixed in https://github.com/GorvGoyl/Notion-Boost-browser-extension/pull/137
