### ISSUE TITLE
Suggestion: indentation lines

### ISSUE THREAD

**Issue by hntxuanit15spkt** [GorvGoyl/Notion-Boost-browser-extension#14]
It's a good idea to have a vertical line to make bulleted list trees easier to follow. Something like the image as follows:
![Screenshot_2](https://user-images.githubusercontent.com/18463138/104949227-2fddfd80-59f1-11eb-956e-39119c1ebf2c.png)

**Comment by TomFrankly** [comment]
Adding a vote for this. It could also be cool to allow these to collapse like Toggles, but the main benefit would be the ability to more easily see indentation position.

**Comment by GorvGoyl** [comment]
> Adding a vote for this. It could also be cool to allow these to collapse like Toggles, but the main benefit would be the ability to more easily see indentation position.

Thanks Frank, Indentation lines are coming in the upcoming update! Toggling of blocks and headings is bit more complicated so might take a little more time.

PS: Huge fan of your videos 😊🙌

**Comment by GorvGoyl** [comment]
done https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/b9122debdd593ff1c0b1355a2b51d90a044cd4dc
