### ISSUE TITLE
The edge browser cannot be used, there is no open button after installation.

### ISSUE THREAD

**Issue by song-hailong** [GorvGoyl/Notion-Boost-browser-extension#150]
The edge browser cannot be used, there is no open button after installation.

![image](https://user-images.githubusercontent.com/38578501/184868892-6a4ba726-6464-4efc-a505-4c44f8c654bc.png)
![image](https://user-images.githubusercontent.com/38578501/184868966-6eb7a28b-a489-4b77-a97f-c98ab87c7713.png)
![image](https://user-images.githubusercontent.com/38578501/184868984-b38080bf-4ff1-49eb-a59e-94f35f08126b.png)

**Comment by Michael679089** [comment]
I'm using an Edge Browser and it works.

![image](https://user-images.githubusercontent.com/90962435/188091990-ac6aca80-e743-4593-b7dd-ca09635650a0.png)

**Comment by GorvGoyl** [comment]
>
