### ISSUE TITLE
Add Scroll to Top Button on top of the Outline

### ISSUE THREAD

**Issue by bFooz** [GorvGoyl/Notion-Boost-browser-extension#158]
Hi, It would be nice to have some kind of "Scroll to Top" button at the top of the outline.

This could be in a form of the page title as the page title is the ultimate heading for the page and all H1..3 headings are sub-headings.

Having this on top would make sense also becuase if I want to go to the top, I go to the top. With the current "Scroll to top" button on the bottom of the page, I have to go down to it when I want to go up.

**Comment by GorvGoyl** [comment]
implemented in upcoming release

**Comment by bFooz** [comment]
This is a great addition. One thing I find confusing from the user perspective is that nothing in the "OUTLINE" title indicates it is functioning like this.

One solution might be to change the "OUTLINE" text to the page name. It is probably obvious that this list on the side of the screen is an outline so it does not need to be so specified.
Another solution might be to place some icon over there next to the "OUTLINE" text.

Check out Coda if you have not already, it has a similar feature (outline) implemented natively.
