### ISSUE TITLE
bug: hide outline button disappeared 

### ISSUE THREAD

**Issue by dontbreakit** [GorvGoyl/Notion-Boost-browser-extension#171]
Hi, I've just noticed that both addons for Chrome 3.2.1 and Firefox 3.2.0 versions do not provide the ability to hide outlines.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/119401705/221800493-0ad072e8-98de-4063-9fde-616f0f7a8515.png">

**Comment by chiperman** [comment]
I have the same problem, I use Edge but also didn't work in Chrome.
My Edge version is 110.0.1587.69 official.

**Comment by zyt0002** [comment]
Me too, recently the button disappeared.

**Comment by king-nex** [comment]
same problem, doesn't help when the outline was already conflicting with the position of the comments. Unusable for any page that has comment now.

**Comment by GorvGoyl** [comment]
fixed in 3.2.2, wait for it go live.
