### ISSUE TITLE
【样式建议】现在的图片frame样式去掉阴影感觉会更加美观

### ISSUE THREAD

**Issue by ronnywr** [GorvGoyl/Notion-Boost-browser-extension#182]
You can refer to the stroke style of the image below
<img width="844" alt="image" src="https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/38126770/c5fc94d3-857e-4db3-a7c5-e4d894cb8d14">

**Comment by joansnotion** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by GorvGoyl** [comment]
please resubmit in english
