### ISSUE TITLE
【功能建议】统一图片宽度

### ISSUE THREAD

**Issue by ronnywr** [GorvGoyl/Notion-Boost-browser-extension#183]
I hope to be able to quickly set the width of the image, and set the width of the current page so the image with one click. For example, the uniform image width is one-quarter, one-third, one-half, and full width of the page width
<img width="500" alt="image" src="https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/38126770/72491ca8-41c8-4fe7-8dd5-7e0460634965">

**Comment by GorvGoyl** [comment]
out of scope
