### ISSUE TITLE
Hide Notification Button Not Working

### ISSUE THREAD

**Issue by manuel-brandt** [GorvGoyl/Notion-Boost-browser-extension#185]
Hi!

I got this extension basically only for the purpose of hiding the notification button. However, all it does is hiding some page icons in the breadcrumbs but not the notification icon. 

Also the hide help icon feature is not working for me.

Would it be possible to fix this?

Cheers,
Manuel

![Uploading Screenshot 2023-06-15 at 4.42.00 PM.png…]()

**Comment by ciqujmeoh77** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by GorvGoyl** [comment]
fixed in upcoming release
