### ISSUE TITLE
The outline feature does not work in Notion. How come?

### ISSUE THREAD

**Issue by SuremyTse** [GorvGoyl/Notion-Boost-browser-extension#189]
Suddenly the outline feature does not work. What is going on? Please help out

**Comment by song-wensong** [comment]
I came cross the same question. Outline doesn't work no matter if I use Edge or Google Chrome.

**Comment by StaircaseWit** [comment]
Having the same issue myself on a Brave Browser

**Comment by boxizen** [comment]
> Fixed the bug and released it on Chrome web store v3.2.3. Please wait for it to go live.
> 
> https://chrome.google.com/webstore/detail/notion-boost/eciepnnimnjaojlkcpdpcgbfkpcagahd?hl=en-GB&authuser=0

I used v3.2.3, but still got this problem.

**Comment by LanthirLM** [comment]
> > Fixed the bug and released it on Chrome web store v3.2.3. Please wait for it to go live.
> > https://chrome.google.com/webstore/detail/notion-boost/eciepnnimnjaojlkcpdpcgbfkpcagahd?hl=en-GB&authuser=0
> 
> I used v3.2.3, but still got this problem.

Me too

**Comment by freyahackingcode** [comment]
Same problem here.
