### ISSUE TITLE
"Add more height to page" not working in Chrome

### ISSUE THREAD

**Issue by JHills3** [GorvGoyl/Notion-Boost-browser-extension#193]
This feature no longer: "add more height to page by hiding top padding, image cover, & icon". Currently it only reduces the space between an icon and the title. 

Add more height turned off:
![image](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/90083925/3065a306-aa3b-49a1-9227-a09d7dc98d55)

Add more height turned on:
![image](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/90083925/b16d55ea-1c60-43e9-833b-df659bc1fccb)

**Comment by joansnotion** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by GorvGoyl** [comment]
fixed in upcoming release
