### ISSUE TITLE
Full width for all pages by default not working

### ISSUE THREAD

**Issue by MJBPopeye** [GorvGoyl/Notion-Boost-browser-extension#195]
Hello, I am not certain how or why this happened. But sometime between last night & this morning something went goofy with this extension. It's always run smooth in the background sine I first installed it when it was a brand new app and never had any trouble with it. 
The entire reason I have enjoyed this extension and downloaded it in the first place was to have the full page width always set when I opened a new page. 
Now, for some reason, ALL of my pages reverted back to the Notion default of starting in the middle. This is happening on all of my pages, even those that are a couple years old...not just new ones. 
I have already uninstalled the extension, cleared all signs of it from cache, etc, closed down chrome, reopened it, reinstalled the extension....none of this worked. 
Please let me know if this is happening to others & how I can fix this issue.
Thanks so much

**Comment by MrFrong604** [comment]
The same issue. Was working great until recently. Following.

**Comment by MJBPopeye** [comment]
Any update on this issue? I have uninstalled and reinstalled, cleared
chrome cache, and done everything I know to do and still not working. Maybe
I am doing something wrong? Please advise next steps.
Thanks so much for your help!





Melissa Basham

Owner | Basham Landscape Management

(M) 832-628-9871

***@***.***

**Comment by GorvGoyl** [comment]
Hi, thanks for reporting the bug. I'm currently occupied with building my
startup but I'll try to find some time to fix it.

**Comment by segolene-tow** [comment]
Hello, 
do you have any clue on when the bug will bi fixed ? 
thank you

**Comment by ipince** [comment]
Hi, I'm running into this problem too.

@GorvGoyl maybe if you point us in the right direction, someone from the community can submit a PR fix?

**Comment by GorvGoyl** [comment]
fine I'll look into it today

**Comment by GorvGoyl** [comment]
fixed in upcoming release
