### ISSUE TITLE
Full width no longer working

### ISSUE THREAD

**Issue by CornerStar** [GorvGoyl/Notion-Boost-browser-extension#197]
Hasn't been working for one or two weeks now.
Every page has to be checked to be "full width" manually again.

**Comment by MrFrong604** [comment]
The same issue. Was working great until recently. Following.

**Comment by allut123** [comment]
I have meet the same issue. This function is no longer to work.

**Comment by MrFrong604** [comment]
Ditto..... Full width for all pages was the only reason why I got this
extension 😭😭😭

**Comment by ciqujmeoh77** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by GorvGoyl** [comment]
fixed in upcoming release
