### ISSUE TITLE
Full width pages by default no longer working

### ISSUE THREAD

**Issue by MrFrong604** [GorvGoyl/Notion-Boost-browser-extension#198]
Guess I'll chime in on this as well.

**Comment by joansnotion** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by Alx-Rlja** [comment]
same issue for me.

**Comment by GorvGoyl** [comment]
fixed in upcoming release
