### ISSUE TITLE
Notion Boost is not working at all.

### ISSUE THREAD

**Issue by rickj64** [GorvGoyl/Notion-Boost-browser-extension#199]

**Comment by amejiarosario** [comment]
I'm having the same issue. When I click on the extenstion just show me some menu without toggles nor sidebar
![image](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/418605/0462356b-7f15-4e6e-a056-1b9ac2fd7231)

@GorvGoyl any ideas?

**Comment by ciqujmeoh77** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

**Comment by seiferflo** [comment]
Same here with Firefox 122. 

Thanks @ciqujmeoh77 Notion Mate looks great but doesn't exist for Firefox...

**Comment by GorvGoyl** [comment]
fixed in upcoming release
