### ISSUE TITLE
Unable to Click on Gallery when Small Text is Selected

### ISSUE THREAD

**Issue by tdon1713** [GorvGoyl/Notion-Boost-browser-extension#2]
If I toggle on the small text and full width setting on a page that is already set to small text and full width within notion settings and that page contains a gallery database, the only columns of the gallery that can be clicked are the far right ones (the gallery that is visible has 25 items, but I don't think that matters)

**Comment by DushiRox** [comment]
+1

**Comment by GorvGoyl** [comment]
it's fixed now in v1.5.1. please restart chrome and test.
