### ISSUE TITLE
Paste as text

### ISSUE THREAD

**Issue by nmeier** [GorvGoyl/Notion-Boost-browser-extension#20]
Often I want to dump some text I copied from another website or a pdf file into my notes. Notion treats the text as formatted and I end up with newlines that break the text into text blocks. I have to manually go through and re-flow the text.

If there was a way to paste-as-text while pressing e.g. shift, or a toggle in the notion boost tool, that would improve my workflows. Thanks

**Comment by GorvGoyl** [comment]
this is more suited at OS level rather than a chrome extension. I think something like `ctrl+shift+v` already exist for that. try googling for "paste without formatting in mac/windows".

**Comment by nmeier** [comment]
yeah, it's kind of not-so-notion but rather OS-ish. One callout though - ctrl+shift+v removes formatting but doesn't remove newlines. If you select text across html tables or a couple of rows in PDF then all paste operations create multiple lines (blocks in notion). There's something here that would making dumping text easier. Food for thought if someone sees this and has an idea how to handle

**Comment by GorvGoyl** [comment]
I do get that requirement, there are other utility tools built for this which would do clipboard text formatting and not limited to just chrome browser like ditto (https://ditto-cp.sourceforge.io/) , phraseexpress, autohotkey, espanso etc.
