### ISSUE TITLE
Missing emoji in outline 

### ISSUE THREAD

**Issue by SFYeh** [GorvGoyl/Notion-Boost-browser-extension#200]
I used to use the 'windows+.' emoji ❤🔹◾☘ to manage my headline to make the hierarchy more clear in outline.
However, recently, these colorful emoji cannot show in outline anymore, could you please figure out why?

**Comment by ciqujmeoh77** [comment]
you can try Notion Mate

https://handy-humidity-660.notion.site/Notion-Mate-f0d639e5f48d4aeabde46f1fabb66a82

![image](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/126656185/b9616459-68cc-407b-9fb7-ab86bbb59c0c)

**Comment by GorvGoyl** [comment]
seems fine to me
![screenshot 2024-01-28 at 19 02 11@2x](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/7106086/b1cf1bb0-e751-4e5d-b92b-36c10272b165)
