### ISSUE TITLE
In-line database width is buggy if outline and full width are turned on

### ISSUE THREAD

**Issue by hrtang** [GorvGoyl/Notion-Boost-browser-extension#201]
With `Full width = True`, the leftmost and rightmost parts of the in-line database is hidden or occluded. This is true for any in-line database display types, such as calendar and table.
<img width="1434" alt="image" src="https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/9334456/ec7a1e04-f7c9-408e-8958-0e92100c224e">

With `Full width = False`, the entire database is visible.
<img width="1431" alt="image" src="https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/9334456/50dcee93-4ff4-4240-8bee-d1c83ffcfa28">

**Comment by ciqujmeoh77** [comment]
you can try Notion Mate extension.

**Comment by GorvGoyl** [comment]
fixed in upcoming release
