### ISSUE TITLE
[Bug] Click outline can not jump to the destination

### ISSUE THREAD

**Issue by JasonAri** [GorvGoyl/Notion-Boost-browser-extension#207]
The outline cannot be clicked to navigate to the corresponding content.

Please Help!

**Comment by BlakeLatch** [comment]
I noticed that this issue occurs when you either:
1. Interact with the page
2. Scroll too far

**Comment by JasonAri** [comment]
> I noticed that this issue occurs when you either:
> 
> 1. Interact with the page
> 2. Scroll too far

Can not jump. Help! TT

https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/96458454/6d813d9b-bf4b-4065-b8e3-83ddaa5c1605

**Comment by FernandoBasso** [comment]
Does it happens with other browsers or even after you refresh the page?

**Comment by BlakeLatch** [comment]
Haven't tried with other browsers but a refresh makes it work briefly until it stops again

**Comment by JasonAri** [comment]
> Does it happens with other browsers or even after you refresh the page?

Refreshing the page doesn't help, the issue  happens to me for long time.
Have tried in Edge, the outline feature doesn't work directly.

**Comment by JasonAri** [comment]
I think I've found the reason, it's conflicting with chandle plugin. lol
