### ISSUE TITLE
Some features like "Outline" doesn't seem to work now

### ISSUE THREAD

**Issue by znre** [GorvGoyl/Notion-Boost-browser-extension#208]
I just noticed that the "Outline" portion doesn't work anymore as well as the "scroll to top" button.

**Comment by Jwindler** [comment]
I also encountered this problem。 @GorvGoyl @twolfson @znre

**Comment by Jasonsey** [comment]
+1

**Comment by JuliusJacobitz** [comment]
+1

**Comment by WheelChen** [comment]
+1

**Comment by archarlotte** [comment]
+1

**Comment by JasonAri** [comment]
Seem to me.

**Comment by JasonAri** [comment]
Same to me.

**Comment by XDzzzzzZyq** [comment]
same

**Comment by keepframe** [comment]
same

**Comment by keepframe** [comment]
I tried another extension for a temporary transition，it is [notion mate](https://chromewebstore.google.com/detail/notion-mate/pplckfedebdimphneohkmhlmhompgpmn)

**Comment by Willxn** [comment]
+1

**Comment by HireTheHero** [comment]
+1

**Comment by GorvGoyl** [comment]
looking into it

**Comment by znre** [comment]
Thanks for fixing it!

But it seems the "scroll to top" button still doesn't work.
