### ISSUE TITLE
Bug: outline don't support emoji

### ISSUE THREAD

**Issue by GKoil** [GorvGoyl/Notion-Boost-browser-extension#27]
<img width="960" alt="chrome_LRHGbBf30n" src="https://user-images.githubusercontent.com/33805170/113547696-9817a500-9618-11eb-86e8-0a45698c82c4.png">

**Comment by GorvGoyl** [comment]
emojis added from notion menu are rendered as image not text, hence not shown in outline. Standard emojis work fine (look how to enter emoji from windows or mac). 

![image](https://user-images.githubusercontent.com/7106086/115143157-45e87200-a063-11eb-81f1-5ce8f1fd0e02.png)

**Comment by GKoil** [comment]
notion automatically change standart emoji 🤷‍♀️

**Comment by GorvGoyl** [comment]
how are you inserting emoji? do not use notion emoji picker.. use your system emoji picker.

**Comment by GKoil** [comment]
@GorvGoyl i use system emoji picker (win + .)
![](https://dl.dropboxusercontent.com/s/ht40wdvlftw35bo/ZzSGP35lga.gif)

**Comment by GorvGoyl** [comment]
ah i see it converts when you focus away, thanks for reporting

**Comment by GorvGoyl** [comment]
fixed in upcoming release.

**Comment by ebanDev** [comment]
Hi ! This still doesn't seem fixed :/
