### ISSUE TITLE
Bug: The full width feature doesn't seem to work

### ISSUE THREAD

**Issue by AnishDe12020** [GorvGoyl/Notion-Boost-browser-extension#28]
So I found out this extension yesterday and have downloaded it for mainly 3 reasons - 
- Full Width for all pages
- Show Outline
- Bold Text in Dark Mode

I enabled the Full Width Feature but whenever I go to a page or even create a new page, full width doesn't get enabled for those pages. Please look into it as I was looking for that feature for a long time and a fix will be appreciated!!! Otherwise it is a really nice extension.

**Comment by GorvGoyl** [comment]
> create a new page

I can reproduce the full width issue. will fix.

> go to a page

For me, full width is working fine. could you elaborate how are you going to new page. any steps to reproduce this issue?

**Comment by AnishDe12020** [comment]
It seems to be working fine fine now and fixed. I will close the issue
