### ISSUE TITLE
Auto dark mode when system dark theme is turned on or off

### ISSUE THREAD

**Issue by gitlater** [GorvGoyl/Notion-Boost-browser-extension#3]
I would like to see the automation of the keystroke **Ctrl+Shift+L** to initiate Notion's native dark mode. As of lately, notion is sill one of the few popular web apps that hasn't added this feature. If this feature can be established, it would be helpful for a lot of user having that dark mode automation goodness.

**Comment by GorvGoyl** [comment]
this is now implemented by notion itself. 
![image](https://user-images.githubusercontent.com/7106086/105741803-bdc16780-5f60-11eb-88ec-9c46465896fb.png)
