### ISSUE TITLE
Using standard tables (Utilisation de tableaux standard)

### ISSUE THREAD

**Issue by VirginieBouvarel** [GorvGoyl/Notion-Boost-browser-extension#34]
Bonjour, je trouve qu'il manque la possibilité d'utiliser des tableaux standards dans notion. Je parle des tableaux réalisables ainsi en markdown : 

| First Column | second column |
|---------------|------------------|
| Content        | content             |

Actuellement on ne peut pas simplement présenter une info sous forme de tableau et ça me manque au quotidien.
Merci pour ce que vous faites.

**Comment by GorvGoyl** [comment]
Translation
```
Hello, I find that the possibility of using standard tables in notion is missing. I'm talking about the tables that can be done in markdown:


Currently we can not simply present an info in the form of a table and I miss it on a daily basis.
Thanks for what you do. 
```

This seems a bit challenging but I'll see if there's a way to implement it

**Comment by GorvGoyl** [comment]
closing due to non-feasibility.
