### ISSUE TITLE
Feature Request: Collapsable Headers / Sections

### ISSUE THREAD

**Issue by away168** [GorvGoyl/Notion-Boost-browser-extension#35]
Similar to Toggle feature, but being able to collapse an entire section just by Header.

**Comment by GorvGoyl** [comment]
hey, that's actually on my to do list. Will move that up on priority. thanks for feedback.

**Comment by sugarpusher** [comment]
Hi there! 
Awesome job with the extension, thank you so much for working on that!
I want to second away168's motion 😁, but especially for the properties section on a database page. Some databases have a lot of properties and you/we have to scroll down a lot to get to the actual content of the page. Being able to hide that would be awesome.
Once again thank you for your hard work on this!

**Comment by GorvGoyl** [comment]
@sugarpusher Did you mean to hide page properties? if so, Notion already has this option:-
![image](https://user-images.githubusercontent.com/7106086/123073257-e37d6a80-d433-11eb-876c-2e71423269db.png)

**Comment by sugarpusher** [comment]
@GorvGoyl  
Thanks for your reply!

Hmm I see your point. I was thinking more like a single toggle that would show/hide them all at once but I guess you can achieve that using the native option after the initial setup. I thought you'd have to set it up for every page but that doesn't seem to be the case.
Either way, you helped me solve my problem. 😊

Thanks again!

**Comment by TomFrankly** [comment]
Adding a vote for this!

**Comment by GorvGoyl** [comment]
closing as this is implemented by Notion itself.
