### ISSUE TITLE
Title with hyperlink does not show in outline.

### ISSUE THREAD

**Issue by rita506011** [GorvGoyl/Notion-Boost-browser-extension#37]
If title (type is #, ## ,###), any text with hyperlink, then it does not show in outline.

**Comment by GorvGoyl** [comment]
Thanks for letting me know, will fix it in next release

**Comment by rita506011** [comment]
Glad to see your reply, thanks your extension. It is really help to me.

**Comment by GorvGoyl** [comment]
fixed in https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/447926220778046cddacb8bea879a13a705a4287
