### ISSUE TITLE
Full width for all pages won't work with grammarly

### ISSUE THREAD

**Issue by blacksnail789521** [GorvGoyl/Notion-Boost-browser-extension#41]
![image](https://user-images.githubusercontent.com/5949636/128668221-4540b591-e031-455e-bbb8-762b1bfc851d.png)

**Comment by GorvGoyl** [comment]
fixed https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/3cf5f8a424780397cb761f5590786d50823de28b
