### ISSUE TITLE
Feature Request: Make Rollup URLs and Notion Pages clickable

### ISSUE THREAD

**Issue by TomFrankly** [GorvGoyl/Notion-Boost-browser-extension#43]
Not sure if this is possible, but Notion hasn't implemented it yet and I figure it'd be doable in Notion Boost for URLs at least!

**Comment by GorvGoyl** [comment]
@TomFrankly working on the url part.. I need some clarification on Notion pages in rollups, do you have any example for it?

**Comment by TomFrankly** [comment]
Yep - here's a Rollup property that's listing specific Notion pages:

![image](https://user-images.githubusercontent.com/684961/132548797-dffb3931-d5f1-44c5-a074-fb8613633e0c.png)

While the output looks identical to what you'd get with a relation, you can't actually click over to this page. Clicking merely brings up the Rollup options.

Not sure if this will be possible to fix through an external extension though. If you're able to get URLs working, that'd still be stellar!

**Comment by GorvGoyl** [comment]
Got it. unfortunately Notion doesn't expose the url behind the page name so it's not possible to build a link for it. However, good news is I'm able to do it for URLs as these are directly visible in the table :)

**Comment by GorvGoyl** [comment]
done https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/69855e456f9496848a402ec2de9f8218be55e666

**Comment by TomFrankly** [comment]
Glad to see this was possible! Do you have an ETA on when this will be committed to the public extension?

**Comment by GorvGoyl** [comment]
hopefully before this weekend 🤞
