### ISSUE TITLE
Add more height to page no longer hides icons and has different padding/spacing

### ISSUE THREAD

**Issue by JHills3** [GorvGoyl/Notion-Boost-browser-extension#46]
"Add more height to page by hiding top padding, image cover, & icon."

This feature no longer hides the icon, and the padding is different for me.

With the feature turned off:
![image](https://user-images.githubusercontent.com/90083925/132084719-87301a30-0be6-45e5-bab1-872defa52908.png)

With the feature turned on:
![image](https://user-images.githubusercontent.com/90083925/132084734-d77c000b-fa25-4823-98f5-64f871b24b52.png)

Hoping that I am just missing something simple, thanks.

**Comment by GorvGoyl** [comment]
thanks for reporting it. will fix.

**Comment by GorvGoyl** [comment]
fixed #0904dcc
