### ISSUE TITLE
settings do not "stay" after rebooting computer/restarting Chrome

### ISSUE THREAD

**Issue by kaya-toast** [GorvGoyl/Notion-Boost-browser-extension#48]
Hello! Thanks for creating the extension. I really enjoy the ability to narrow the line height of lists. I encounter a problem, however. Whenever I reboot my computer and go to my notion page again, none of the settings I selected in the extension apply. When I click the extension icon, the toggles are on, but they do not affect the notion page. In order to use the functions, I have to toggle off the features and back on again. To do this whenever I reboot my computer is a bit cumbersome. Thanks for looking into the problem!

**Comment by GorvGoyl** [comment]
when you put pc to sleep, all browser extensions become inactive. it's the browser behaviour.
Did you try reloading notion page Instead of toggling features?

**Comment by kaya-toast** [comment]
that fixed it! thank you!
