### ISSUE TITLE
Table improvements

### ISSUE THREAD

**Issue by r2d2m** [GorvGoyl/Notion-Boost-browser-extension#5]
Hi ! Let me start by saying this extension is awesome.

I don't know if this fits the scope of the expansion, but I think it has the potential of becoming really great with many little quirks added

I have lots of tables in notion, and something missing for me is a better table management.

I'd like to add Odd / Even coloration, something like : 
tr:nth-child(even) {background: #CCC}
tr:nth-child(odd) {background: #FFF}

And if it's possible (I don't know how to start with this), fixed header for tables, and first column ?

**Comment by GorvGoyl** [comment]
Thanks for the kind words. 

> I'd like to add Odd / Even coloration, 

That's a neat suggestion. will add to to-do list.

>fixed header for tables,

Header is already fixed if you scroll down the table (atleast in my case). does this not happen for you?

> and first column ?

That's also a good idea for tables with large no. of columns. Will see if it can be done.

**Comment by r2d2m** [comment]
Actually, it does happen for me ! Guess I never paid attention to it :p

**Comment by fcherman** [comment]
> …it does happen for me ! Guess I never paid attention to it :p

Actually, the fixed header happens only on full-page databases. It does not happen when the table is inline, and I wish very much that it did. The lack of a fixed header row on inline tables makes them practically useless for me. What I would like is for the header to scroll with the table until it reaches the top of the viewport, where it would then stay put until and unless I scroll _past_ the table to other elements on the page. Is this possible?

**Comment by GorvGoyl** [comment]
fixed header happens for both inline and full page tables. I wonder why it's not happening for you.

**Comment by fcherman** [comment]
Good question. I'll investigate further.
