### ISSUE TITLE
Full width has not worked since yesterday.

### ISSUE THREAD

**Issue by tianyunperfect** [GorvGoyl/Notion-Boost-browser-extension#53]
![image](https://user-images.githubusercontent.com/23491291/134791871-eb7ed8ba-cfab-4e59-94b1-6ddde8847876.png)
Full width has not worked since yesterday.

**Comment by GorvGoyl** [comment]
could you update the browser extension and re-start the browser.

**Comment by tianyunperfect** [comment]
> could you update the browser extension and re-start the browser.

I reinstalled the plug-in and then rebooted the browser, but it still doesn’t work. Is there something wrong with me?

**Comment by GorvGoyl** [comment]
could you tell me the extension version installed. you can see it from inside extension -> about

**Comment by tianyunperfect** [comment]
> could you tell me the extension version installed. you can see it from inside extension -> about

3.0.1

**Comment by GorvGoyl** [comment]
thanks for reporting. It'll be fixed in upcoming update

**Comment by GorvGoyl** [comment]
fixed
