### ISSUE TITLE
"Small Text On All Pages" is broken

### ISSUE THREAD

**Issue by PatinaPhoto** [GorvGoyl/Notion-Boost-browser-extension#54]
Page blocks added to a column view have a huge text size applied to them (see screenshot) when "small text on all pages" is turned on. This Notion Boost css seems to the be problem: 
`.smallText .notion-scroller.vertical>div>div>div:nth-child(1) div.notion-selectable.notion-page-block`

**Screenshot 1: "Small Text On All Pages" turned on**
(Note how the full width page block does not have this issue, only page blocks in a column view)
![Screenshot 2021-09-27 094428](https://user-images.githubusercontent.com/91435585/134823567-1998b88e-cc83-4921-acb6-fa4606c0c570.jpg)

**Screenshot 2: "Small Text On All Pages" turned off**
![Screenshot 2021-09-27 094500](https://user-images.githubusercontent.com/91435585/134823626-a0e971cc-a676-4257-b0cd-3dad2f283a91.jpg)

**Comment by GorvGoyl** [comment]
I've deployed the new update with the fix. should be available soon on chrome and firefox store.

**Comment by GorvGoyl** [comment]
background on issue: It happened because notion recently changed styling for their pages which led to issues with small text feature.
