### ISSUE TITLE
"Small text for all pages" is suddenly making text big!

### ISSUE THREAD

**Issue by vnavone** [GorvGoyl/Notion-Boost-browser-extension#55]
I'm using Pro version of 3.0.1 in Chrome and today I noticed that my page links have become giant - about the size of Header 1.  Database contents and regular text blocks are not are not affected.  I have disabled this toggle for now but I'm hoping you can fix this quickly!

**Comment by GorvGoyl** [comment]
duplicate of https://github.com/GorvGoyl/Notion-Boost-browser-extension/issues/54
