### ISSUE TITLE
Additional "Don't show slash menu" nuances

### ISSUE THREAD

**Issue by twolfson** [GorvGoyl/Notion-Boost-browser-extension#62]
I've started using Notion more regularly and am bumping into the following cases where our override for / seems to misbehave:

- If a line is empty, then typing / should prob show the menu
- If we type / inside of a table, it exits the table (and in Firefox open "Quick Find" O_O)
- If we type / in a subpage pop-up, it temporarily hides the page (and same "Quick Find" behavior in FF)

If I disable the Notion Boost setting, then the normal functionality works for these =/

**Comment by twolfson** [comment]
I did some poking around, implementation-wise the first 2 should be relatively easy:

- We can find the currently selected line by finding the `+` and `::` elements. The latter has a `data-block-id` which seems to correspond to the current line, and so we can find the content that way
- When editing a field in a table there's a `data-overlay=true` element that opens up
    - However, subpages also seem to use this `data-overlay=true` so there's prob some heuristics to determine what type of overlay


- I'm guessing for subpages we need to click in a different location than the current default and that should be all


This feature will keep on growing/exploding I feel though, so before diving in, it seems like there should be a robust testing framework around all this =/ (though it's always sensitive to "what if Notion does a UI redesign"). Is that something that exists?

**Comment by GorvGoyl** [comment]
> If a line is empty, then typing / should prob show the menu

this one seems to be an odd behaviour.. If user wants to disable slash command then it should get disabled entirely.

Other 2 points are bugs and should be resolved.

There's no automated testing framework (I've never tried tbh) so I usually write all test cases and manually test whether things are working fine or not.
