### ISSUE TITLE
Hide 'Hidden columns' in board view

### ISSUE THREAD

**Issue by johnobogne** [GorvGoyl/Notion-Boost-browser-extension#64]
The 'Hidden columns' column still appear.

![image](https://user-images.githubusercontent.com/23580313/136917355-f321f91e-f29f-405b-ba5a-4bd1d8049fa6.png)

**Comment by poeticua** [comment]
Seconding this. Worked well for a long time but no longer works.

**Comment by GorvGoyl** [comment]
fixed in upcoming release

**Comment by GorvGoyl** [comment]
fixed
