### ISSUE TITLE
Notion Boost | Rollup Disfunction

### ISSUE THREAD

**Issue by StanislasBASQUIN** [GorvGoyl/Notion-Boost-browser-extension#67]
Subscriber for **Notion Boost**. I am not able to click on **URL Rollup**.
Attached _Screenshot_ in which you can see the situation in Chrome Browser. 
Your's, Stanislas

![TROUBLESHOOTING_NotionBoost](https://user-images.githubusercontent.com/7883526/139849646-384b385d-d1fd-4581-a29a-dc81087737c2.png)

**Comment by GorvGoyl** [comment]
Thank you for notifying me. I'll look into the issue.

**Comment by GorvGoyl** [comment]
fixed in upcoming release

**Comment by GorvGoyl** [comment]
fixed
