### ISSUE TITLE
Scroll to top button not appearing in 4K screens

### ISSUE THREAD

**Issue by jahirfiquitiva** [GorvGoyl/Notion-Boost-browser-extension#68]
It appears if I resize the window to be less tall

**Comment by GorvGoyl** [comment]
thanks for reporting the issue. I'll look into it.

**Comment by jahirfiquitiva** [comment]
thanks!

**Comment by GorvGoyl** [comment]
Scroll to top button would appear if you scroll 100% of the page height. Let me know if there's any other issue

**Comment by jahirfiquitiva** [comment]
any chance to make it appear at 90% or to add an option to customize that?
