### ISSUE TITLE
Outline conflicts with new Notion comments

### ISSUE THREAD

**Issue by hofmannjan0** [GorvGoyl/Notion-Boost-browser-extension#70]
Hi there, 

Notion currently provided an update which changed the way comments are displayed. This causes a problem with Notion boost. If the outline is displayed on the right side, the comments block parts of the content. This does only happen with the Notion boost outline and it happens regardless of the browser window width.

Since Notion boost is a third party tool, I don't think that the Notion team takes such an issue into account so I'm reaching out to you.

Release notes for the update (see section "better comments"):
https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c#d116fc91bbfb45c1976de036f6c7731f

Outline hidden:
![image](https://user-images.githubusercontent.com/7526096/142044959-76d5cfc7-e2b6-4f1e-a050-a79341e83712.png)

Outline enabled:
![image](https://user-images.githubusercontent.com/7526096/142045116-7f32d3d6-e5b8-4912-98fa-0e578abae427.png)

Screen size does not matter:
![image](https://user-images.githubusercontent.com/7526096/142045320-ba0f7d91-b07e-40be-9030-275581a4b3f6.png)

**Comment by GorvGoyl** [comment]
Thanks for reporting the issue. I'll look into it.

**Comment by GorvGoyl** [comment]
So I looked into this and comments are overlapping content because there's not much space left on the page. For wider screens comment box is not overlapping in my case.

**Comment by hofmannjan0** [comment]
Hi @GorvGoyl,

thanks for looking into the issue. It still persists for me. Also, the outline also conflicts with the new simple tables added with the latest update of Notion. Tables get pushed to the left when the Outline is displayed, just like the comments.

![chrome-capture](https://user-images.githubusercontent.com/7526096/144301229-107e63ed-afb8-4543-844f-891df431e61d.gif)

**Comment by GorvGoyl** [comment]
fixed (v3.0.6). let me know if issue still persists.
