### ISSUE TITLE
When showing the outline, the new simple table looks strange

### ISSUE THREAD

**Issue by KyrieHuang666** [GorvGoyl/Notion-Boost-browser-extension#72]
Notion just released a new function called "simple table", but it seems that it doesn't fit so well with the notion boost. It looks like this
![Snipaste_2021-11-17_12-40-52](https://user-images.githubusercontent.com/61863863/142136324-7ea37cb7-7e7b-45d8-b0b4-e81805b45a4f.png)
is

**Comment by GorvGoyl** [comment]
Could you provide more details.
Table is working fine for me:

![image](https://user-images.githubusercontent.com/7106086/143721373-1b1186bd-9686-4990-b7dd-b41b554c67d1.png)

**Comment by GorvGoyl** [comment]
Able to reproduce the issue. Will be fixed in upcoming release

**Comment by GorvGoyl** [comment]
fixed.
