### ISSUE TITLE
Open the outline in the dark mode, causing a white block in the lower right corner

### ISSUE THREAD

**Issue by xiaoyoucheng** [GorvGoyl/Notion-Boost-browser-extension#77]
Open the outline in the dark mode, causing a white block in the lower right corner.
![image](https://user-images.githubusercontent.com/33143581/146149433-5afb4435-1a99-402e-8e5f-75cc1a605efd.png)
Can I put 'nb-outline show' div outside 'notion-frame'?

**Comment by GorvGoyl** [comment]
could you please share which browser is that

**Comment by xiaoyoucheng** [comment]
The above BUG has been repaired.
But there is a new problem.
![30](https://user-images.githubusercontent.com/33143581/154679371-9385742d-c649-4a0e-8253-251b594fc131.gif)
If the field of the database is too much, the effects in the picture will appear.
There is no such situation before, but white squares will appear, it should be caused by two scroll bars.
Windows10, Chrome98
