### ISSUE TITLE
New page button

### ISSUE THREAD

**Issue by CavalloneChen** [GorvGoyl/Notion-Boost-browser-extension#8]
We can't use keyboard shortcut ctrl/cmd+n to quickly create new pages in web version. Please consider adding a new page button to bypass this issue.

**Comment by Freshchris01** [comment]
@CavalloneChen There is a new page button in the left bottom corner. Are you referring to something else or can this be closed?
![new_page_notion](https://user-images.githubusercontent.com/3072291/113130285-33290d00-921c-11eb-8202-24e8a14345fd.png)

**Comment by CavalloneChen** [comment]
That's right. It's okay to close this issue.
