### ISSUE TITLE
The full width feature hasn't been working since last week.

### ISSUE THREAD

**Issue by lightbluepoppy** [GorvGoyl/Notion-Boost-browser-extension#86]
I tried on chrome and Edge but it worked on neither.

**Comment by hntxuanit15spkt** [comment]
I have the same problem as you

**Comment by GorvGoyl** [comment]
thanks. Will fix soon.

**Comment by GorvGoyl** [comment]
fixed https://github.com/GorvGoyl/Notion-Boost-browser-extension/commit/99eb81b4dcb284a0edb2c115c0cec3012100762c
