### ISSUE TITLE
Issue with slash command

### ISSUE THREAD

**Issue by ln123567** [GorvGoyl/Notion-Boost-browser-extension#88]
I have an issue with the slash command features on the Notion Boost extension ('Close slash command menu after space' and 'Don't show slash command menu when pressing '/'). 

With the first command, upon typing out the slash, my cursor automatically moves to the top of the page, or to the heading of the section. With the second command, the cursor automatically moves to either the top of the page or the heading when I press the spacebar after the slash command. 

Occasionally, neither of these happen, but the page jerks a little, which makes for a disruptive typing experience.

**Comment by GorvGoyl** [comment]
thanks. will fix.
