### ISSUE TITLE
Add more height to page no longer hides icons and has different padding/spacing. Repeating issue #46

### ISSUE THREAD

**Issue by JHills3** [GorvGoyl/Notion-Boost-browser-extension#89]
Issue #46 has reoccured: [Add more height to page no longer hides icons and has different padding/spacing](https://github.com/GorvGoyl/Notion-Boost-browser-extension/issues/46) 

![image](https://user-images.githubusercontent.com/90083925/153526050-b1ce6d09-62ac-49c4-b0d1-aba18c827c16.png)

![image](https://user-images.githubusercontent.com/90083925/153526064-82a2e2ae-e602-4c86-ba2a-a32d93518f19.png)

**Comment by GorvGoyl** [comment]
thanks for reporting the issue. will fix it.
